// Frontend-React-TS/src/pages/product/movement/Movement.tsx
import { Button, Row, Form, Table } from "react-bootstrap";
import { DotLoader } from "react-spinners";

import { useMovement } from "./useMovement";

const Movement = () => {
  const { state, stateUpdaters } = useMovement();
  const { loadingPage, data } = state;
  const { product, movements } = data;
  const { handleBack } = stateUpdaters;

  return (
    <>
      <div className="d-flex justify-content-start mb-3">
        <Button
          variant="danger"
          size="sm"
          onClick={handleBack}
        >
          ← Back
        </Button>
      </div>

      {loadingPage ? (
        <div className="mt-5 d-flex justify-content-center">
          <DotLoader
            color="#0d6efd"
            size={100}
          />
        </div>
      ) : (
        <>
          <Row className="mt-3">
            <h3 className="text-center">Product</h3>
          </Row>
          <Form className="p-4 border rounded shadow-sm">
            <Form.Group className="mb-3">
              <Form.Label>Name</Form.Label>
              <Form.Control
                type="text"
                name="name"
                value={
                  product?.name ? `${product?.name} ${product?.code} ${product?.category}` : ""
                }
                required
                disabled
              />
            </Form.Group>

            <Form.Group className="mb-3">
              <Form.Label>Description</Form.Label>
              <Form.Control
                as="textarea"
                rows={3}
                name="description"
                value={
                  product?.description
                    ? `${product?.description}\nPrice: ${product?.price}\nStock: ${product?.stock}`
                    : ""
                }
                required
                disabled
              />
            </Form.Group>
          </Form>

          <Row className="mt-5">
            <h3 className="text-center">Movements Product</h3>
          </Row>
          <div className="pb-4">
            <Table
              className="table-striped table-bordered text-nowrap shadow-sm rounded"
              responsive="md"
            >
              <thead className="table-dark">
                <tr>
                  <th className="text-start">Date</th>
                  <th className="text-start">Type</th>
                  <th className="text-start">Amout</th>
                  <th className="text-center">Description</th>
                </tr>
              </thead>
              <tbody>
                {movements?.map((item) => (
                  <tr key={item.id}>
                    <td className="text-start">{item.date}</td>
                    <td className="text-start">{item.type}</td>
                    <td className="text-start">{item.amount}</td>
                    <td className="text-start">{item.description}</td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </div>
        </>
      )}
    </>
  );
};

export default Movement;

// Frontend-Angular16/src/app/views/product/movement/movement.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute } from '@angular/router';

import { ProductService } from '../services/product.service';
import { Product, Movement } from '../interfaces/productInterfaces';

@Component({
  selector: 'app-movement',
  templateUrl: './movement.component.html',
  styleUrls: ['./movement.component.css'],
})
export class MovementComponent {
  productId!: string;
  loadingPage = true;
  product: Product | null = null;
  movements: Movement[] = [];

  displayedColumns: string[] = ['date', 'type', 'amount', 'description'];

  constructor(
    private service: ProductService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.productId = this.route.snapshot.paramMap.get('id')!;
    this.getData(Number(this.productId));
  }

  getData(id: number): void {
    this.service.GetProductWithMovement(id).subscribe((data) => {
      this.loadingPage = false;
      this.product = data.product || null;
      this.movements = data.movements || [];
    });
  }

  handleBack(): void {
    this.router.navigate(['/product']);
  }
}

<div class="d-flex justify-content-start mb-3">
  <button mat-raised-button color="warn" (click)="handleBack()">← Back</button>
</div>

<ng-container *ngIf="loadingPage; else content">
  <div class="mt-5 d-flex justify-content-center">
    <mat-spinner diameter="80" color="primary"></mat-spinner>
  </div>
</ng-container>

<ng-template #content>
  <div class="mt-3">
    <h3 class="text-center">Product</h3>
  </div>

  <form class="p-4 border rounded shadow-sm">
    <mat-form-field appearance="outline" class="w-100 mb-3">
      <mat-label>Name</mat-label>
      <input
        matInput
        [value]="
          product
            ? product.name + ' ' + product.code + ' ' + product.category
            : ''
        "
        disabled
      />
    </mat-form-field>

    <mat-form-field appearance="outline" class="w-100 mb-3">
      <mat-label>Description</mat-label>
      <textarea
        matInput
        rows="4"
        [value]="
          product
            ? product.description +
              '\nPrice: ' +
              product.price +
              '\nStock: ' +
              product.stock
            : ''
        "
        disabled
      ></textarea>
    </mat-form-field>
  </form>

  <div class="mt-5">
    <h3 class="text-center">Movements Product</h3>
  </div>

  <div class="pb-4">
    <table mat-table [dataSource]="movements" class="mat-elevation-z2 w-100">
      <ng-container matColumnDef="date">
        <th mat-header-cell *matHeaderCellDef>Date</th>
        <td mat-cell *matCellDef="let element">{{ element.date }}</td>
      </ng-container>

      <ng-container matColumnDef="type">
        <th mat-header-cell *matHeaderCellDef>Type</th>
        <td mat-cell *matCellDef="let element">{{ element.type }}</td>
      </ng-container>

      <ng-container matColumnDef="amount">
        <th mat-header-cell *matHeaderCellDef>Amount</th>
        <td mat-cell *matCellDef="let element">{{ element.amount }}</td>
      </ng-container>

      <ng-container matColumnDef="description">
        <th mat-header-cell *matHeaderCellDef>Description</th>
        <td mat-cell *matCellDef="let element">{{ element.description }}</td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
    </table>
  </div>
</ng-template>
